# Generated by Django 4.0.3 on 2022-04-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faq_modify_date_faq_writer_faq_writer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('0', '일반'), ('1', '계정'), ('2', '기타')], default='0', max_length=2),
        ),
    ]
